spring:
  h2:
    console:
      enabled: true  # H2 Console 사용 여부
      path: /h2-console  # H2 Console 접속 URL
      settings: 
        web-allow-others: true
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/jpashop  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
#        show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸

logging:
  org.hibernate.SQL: debug #띄어쓰기 2칸
  level:
    org.hibernate.orm.jdbc.bind: trace
